# Portfolio dev overlay -> creates the dev version of Asmaa's portfolio.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: resume-asmaa-dev

resources:
  - namespace.yaml
  - ../../base

patches:
  - path: patch-image.yaml

replicas:
  - name: asmaa-portfolio
    count: 2

labels:
  - pairs:
      environment: dev