apiVersion: apps/v1
kind: Deployment
metadata:
  name: asmaa-portfolio
spec:
  template:
    spec:
      containers:
        - name: asmaa-portfolio
          image: acrportfoldev.azurecr.io/asmaa-portfolio:v2