# Portflio base -> reused across dev/stage/prod overlays
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - gateway.yaml
  - httproute.yaml

labels:
  - pairs:
      app.kubernetes.io/name: asmaa-portfolio
      app.kubernetes.io/part-of: resume-platform