# This is an ArgoCD Application manifest for deploying the Asmaa Portfolio application in a production environment.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: asmaa-portfolio-prod
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/IceBear1026/Portfolio_Website.git
    targetRevision: main
    path: k8s/apps/asmaa-portfolio/overlays/prod

  destination:
    server: https://kubernetes.default.svc
    namespace: portfolio-asmaa

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true