apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: azure-keyvault-launchmywork
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: "https://kv-launchmywork-prod.vault.azure.net/"
      serviceAccountRef:
        name: external-secrets
        namespace: external-secrets
